version: '3.2'
services:
  hadoop-yarn:
    image: hadoop-yarn
    container_name: hadoop-yarn
    build:
      context: ./..
      dockerfile: docker/hadoop-yarn/Dockerfile
      args:
        - HADOOP_VERSION=$HADOOP_VERSION
    ports:
      - "9870:9870"
      - "8088:8088"
    volumes:
      - /home/kkurek/PycharmProjects/apache-spark-on-hadoop/docker/start-scripts:/start-scripts
    networks:
      - hadoop-network
  spark:
    image: spark
    build:
      context: ./..
      dockerfile: docker/spark/Dockerfile
      args:
        - SPARK_VERSION=$SPARK_VERSION
    volumes:
      - /home/kkurek/PycharmProjects/apache-spark-on-hadoop/docker/spark/execute-script:/execute-script
    networks:
      - hadoop-network
    command: "sleep infinity"
networks:
  hadoop-network:
